# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TEBF0808_mappings.xdc

# Block Designs: bd/testbench_bd/testbench_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testbench_bd || ORIG_REF_NAME==testbench_bd} -quiet] -quiet

# IP: bd/testbench_bd/ip/testbench_bd_zynq_ultra_ps_e_0_0/testbench_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testbench_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==testbench_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/testbench_bd/ip/testbench_bd_test_top_0_2/testbench_bd_test_top_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testbench_bd_test_top_0_2 || ORIG_REF_NAME==testbench_bd_test_top_0_2} -quiet] -quiet

# XDC: bd/testbench_bd/testbench_bd_ooc.xdc
