# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lnis/Documents/GF12_Testbed/src/constr/TEBF0808_mappings.xdc

# Block Designs: bd/blinky_bd/blinky_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd || ORIG_REF_NAME==blinky_bd} -quiet] -quiet

# IP: bd/blinky_bd/ip/blinky_bd_test_top_0_0/blinky_bd_test_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd_test_top_0_0 || ORIG_REF_NAME==blinky_bd_test_top_0_0} -quiet] -quiet

# IP: bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blinky_bd_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==blinky_bd_zynq_ultra_ps_e_0_2} -quiet] -quiet

# XDC: bd/blinky_bd/blinky_bd_ooc.xdc
