# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/testbench_bd/testbench_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testbench_bd || ORIG_REF_NAME==testbench_bd} -quiet] -quiet

# IP: bd/testbench_bd/ip/testbench_bd_processing_system7_0_0/testbench_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testbench_bd_processing_system7_0_0 || ORIG_REF_NAME==testbench_bd_processing_system7_0_0} -quiet] -quiet

# XDC: bd/testbench_bd/testbench_bd_ooc.xdc
