# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2.xci
# IP: The module: 'blinky_bd_zynq_ultra_ps_e_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_bd_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_bd_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2.xci
# IP: The module: 'blinky_bd_zynq_ultra_ps_e_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_bd_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/apond/Documents/GF12_Testbed/projects/blinky/blinky.srcs/sources_1/bd/blinky_bd/ip/blinky_bd_zynq_ultra_ps_e_0_2/blinky_bd_zynq_ultra_ps_e_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_bd_zynq_ultra_ps_e_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
